#!/bin/bash          

echo "This script runs the robot framework tests"

# Prints usage message
usage()
{
    echo "Usage: testall [--token | -t YOUR_TOKEN] [--parallel | -p]"
}

# Detect parameters
parallel=
token=
while [ "$1" != "" ]; do
    case $1 in
        -t | --token )          shift
                                token=$1
                                ;;
        -p | --parallel )       parallel=1
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done


##### Main

# uninstall onc library in case an older version exists
pip uninstall -y onc

if [ "$token" == "" ]; then
    # Kill if no token
    usage
    exit 1
fi

if [ "$parallel" == "1" ]; then
    # Execute tests in parallel
    pabot --testlevelsplit --outputdir report --loglevel DEBUG --variable token:$token suites
else
    # Normal robot execution
    robot --outputdir report --loglevel DEBUG --variable token:$token suites
fi
