#!/bin/bash
echo "This script obtains the code coverage for the robot framework tests"

# Prints usage message
usage()
{
    echo "Usage: testcoverage [--token | -t YOUR_TOKEN]  [--suite | -s SUITE_NUMBER(0-99)]"
}

# Detect parameters
parallel=
token=
suite=
while [ "$1" != "" ]; do
    case $1 in
        -t | --token )          shift
                                token=$1
                                ;;
        -s | --suite )          shift
                                suite=$1
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

# Print test suites if we didn't get a suite number
if [ "$suite" == "" ]; then
    echo "Test suites available:"
fi

# Get a list of test suites
i=0
for file in $PWD/suites/*
do
    filename=$(echo $file | cut -d'/' -f 8)
    names[$i]="$filename"
    ((i++))
done

# run tests
if [ "$suite" == "" ]; then
    echo "Running all tests"
    coverage run -m robot --outputdir report --loglevel DEBUG --variable token:$token suites
else
    echo "Running suite: ${names[$suite]}"
    coverage run -m robot --outputdir report --loglevel DEBUG --variable token:$token suites/${names[$suite]}
fi

# print console report
coverage report --include *onc/*

# generate HTML report
coverage html --include *onc/*
echo HTML report generated at: $PWD/htmlcov/index.html
